[build]
  functions = "functions"
  command = "pip install -r requirements.txt && python generate_posts.py && python generate_index.py"
  publish = "output"

[dev]
  command = "python -m http.server -d output"
